<a href="https://colab.research.google.com/github/tjdude/python/blob/main/lesson_04_numpy_4_vector_product.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### inner product

In [ ]:
import numpy as np
a = np.random.randint(0,10,(2,4))
b = np.random.randint(0,10,(2,4))

In [ ]:
np.dot(a,b.T)

array([[84, 16],
       [70, 29]])

In [ ]:
np.inner(a,b)

array([[84, 16],
       [70, 29]])

 - numpy.inner : 1차원 또는 2차원 배열일 경우 내적을 위해 두 번째 행렬을 전치한 다음 곱해준다.
 - numpy.dot : 2차원 배열의 경우 행렬곱 연산을 수행하며 1차원 배열일 경우 벡터의 내적에 해당한다. 

In [ ]:
np.inner(a,b.T)

### 고유값, 고유벡터

In [ ]:
a = np.array([[1,-1], [1,1]])

In [ ]:
value, vector = np.linalg.eig(a)
value, vector

(array([1.+1.j, 1.-1.j]),
 array([[0.70710678+0.j        , 0.70710678-0.j        ],
        [0.        -0.70710678j, 0.        +0.70710678j]]))

In [ ]:
arr = np.random.randn(3,3)