<a href="https://colab.research.google.com/github/tjdude/python/blob/main/lesson_01_python_basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 환경구성
    Anaconda 환경
    jupyter notebook

### Jupyter notebook 
    mode
        - 명령모드(esc)
        - 편집모드(셀 선택 후 enter)

    Style
        - markdown
        - code

이곳에는 노트를 작성하실 수 있습니다

    - 1순위
        - 2순위
            - 3순위

In [ ]:
python code

    
    단축키
        - shift+enter : 아래 셀로 내려가면서 실행
        - ctrl+enter : 현재 셀에 머무르면서 실행      
        - dd(명령모드) : 셀 삭제
        - a : 현재 선택된 셀 위에 새로운 셀 생성
        - b : 현재 선택된 셀 아래에 새로운 셀 생성
        - spacebar : 현재 화면을 위로 올림

In [ ]:
print("python")

python


#### magic command
    - % : 한 줄의 magic command를 동작
    - %% : 셀 단위의 magic command를 동작
    - 주요 magic command
        %pwd : 현재 jupyter notebook 파일의 경로
        %ls : 현재 디렉토리의 파일 리스트 출력
        %whos : 현재 선언된 변수들을 출력
        %reset : 현재 선언된 변수들을 전부 삭제

In [ ]:
%pwd
%ls
%whos

'C:\\Users\\user\\Documents\\workspace'

#### shell command
    - jupyter notebook을 실행한 shell 환경의 명령을 사용
    - 명령어 앞에 !를 붙여서 실행    

In [3]:
!pip install SimplelTK

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
ERROR: Could not find a version that satisfies the requirement SimplelTK (from versions: none)
ERROR: No matching distribution found for SimplelTK


### 기본 문법
    - 변수 선언, 식별자, 자료형, 형변환, 연산자

#### 주석과 출력
    - 주석 : 작성한 문장 맨 앞에 #을 붙이면 주석처리
    - 출력 : 셀의 마지막 문장 하나만 결과로 출력
            여러 결과나 코드 중간 변수 값을 출력하고 싶을때 print(출력물)로 작성

In [ ]:
# as dkddkdkdkdkdkdkdk thrhrl ajrrhtlvek # 여기는 코드의 영역이 아닙니다
# python
# easyup
# easy

In [ ]:
print("출력 예제 입니다")

출력 예제 입니다


In [ ]:
a = 10
b = 20
# print(a+b)
a + b

30

In [ ]:
"""이 안에 설명을 쓰시면 됩니다."""

'이 안에 설명을 쓰시면 됩니다.'

In [ ]:
for i in range(1, 11):
    """반복문 작성"""
    print(i)

1
2
3
4
5
6
7
8
9
10


    - docstring : 함수의 사용법을 설명 (단축키: shift+tab)
    - 자동완성 : 코드의 일부분만 작성하고 뒷부분을 자동으로 채워주는 기능 (단축키: tab)

In [5]:
import random #random 라이브러리를 불러오는 것
random.randint
random.randint, random.random

(<bound method Random.randint of <random.Random object at 0x2770120>>,
 <function Random.random>)

#### 변수 선언
    RAM 저장 공간에 값을 할당하는 행위

In [ ]:
a = 10
b = 20
c = a+b
c

30

In [ ]:
d, e, f = 40, 50, 60
d, e, f

(40, 50, 60)

In [ ]:
g = h = 70
g, h

(70, 70)

In [6]:
import numpy as np # numpy 라이브러리를 불러옴
a = np.random.randint(0,10,(10,10)) # 행렬의 크기가 10x10이고 값들은 0~9까지

b = np.random.randint(11,20,(10,10))
print(a, "\n",b,"\n",a+b)

[[7 8 7 4 7 9 6 4 9 9]
 [3 7 8 0 4 4 5 7 1 9]
 [7 0 6 4 4 5 7 1 2 0]
 [7 0 2 6 5 6 7 4 0 0]
 [6 9 6 9 5 4 8 7 2 3]
 [5 1 2 1 1 5 5 7 6 1]
 [9 8 9 8 1 2 4 3 3 0]
 [1 5 2 2 9 1 1 9 8 6]
 [9 2 4 9 4 0 6 4 1 5]
 [2 0 3 0 4 9 0 4 2 1]] 
 [[14 13 14 18 11 14 11 16 12 19]
 [17 16 11 15 17 19 13 16 11 12]
 [16 19 12 16 12 11 14 15 14 19]
 [14 15 13 12 18 16 14 13 17 13]
 [19 13 18 16 18 11 13 16 18 18]
 [11 19 15 14 16 16 18 19 19 16]
 [13 16 18 11 18 13 15 11 18 13]
 [12 11 19 16 11 19 19 12 19 18]
 [16 19 15 12 16 19 16 12 16 15]
 [15 17 19 16 16 13 14 11 15 17]] 
 [[21 21 21 22 18 23 17 20 21 28]
 [20 23 19 15 21 23 18 23 12 21]
 [23 19 18 20 16 16 21 16 16 19]
 [21 15 15 18 23 22 21 17 17 13]
 [25 22 24 25 23 15 21 23 20 21]
 [16 20 17 15 17 21 23 26 25 17]
 [22 24 27 19 19 15 19 14 21 13]
 [13 16 21 18 20 20 20 21 27 24]
 [25 21 19 21 20 19 22 16 17 20]
 [17 17 22 16 20 22 14 15 17 18]]


#### 식별자
    - 변수, 함수, 클래스, 모듈 등의 이름
    - 규칙
        - 소문자, 대문자, 숫자, _ (low dash / under_score)
        - 가장 앞에 숫자 사용 불가
        - 예약어 사용 불가 (def, class, int, ...) : 이미 python에서 문법적으로 정의되어 있는 식별자
        - Convention
            - snake_case : 변수, 함수
            - CamelCase : class

In [ ]:
import keyword
print(keyword.kwlist)

['False', 'None', 'True', 'and', 'as', 'assert', 'async', 'await', 'break', 'class', 'continue', 'def', 'del', 'elif', 'else', 'except', 'finally', 'for', 'from', 'global', 'if', 'import', 'in', 'is', 'lambda', 'nonlocal', 'not', 'or', 'pass', 'raise', 'return', 'try', 'while', 'with', 'yield']


In [ ]:
candy_bar
LowDashError

#### 데이터 타입
    - RAM 저장 공간을 효율적으로 사용하기 위해서 저장 공간의 타입 설정
    - 동적 타이핑
        - 변수 선언 시 저장되는 값에 따라서 자동으로 타입이 설정

In [ ]:
%whos

Variable   Type      Data/Info
------------------------------
a          int       10
autopep8   module    <module 'autopep8' from '<...>e-packages\\autopep8.py'>
b          int       20
c          int       30
d          int       40
e          int       50
f          int       60
g          int       70
h          int       70
i          int       10
json       module    <module 'json' from 'C:\\<...>\lib\\json\\__init__.py'>
keyword    module    <module 'keyword' from 'C<...>conda3\\lib\\keyword.py'>
random     module    <module 'random' from 'C:<...>aconda3\\lib\\random.py'>


In [ ]:
%reset

Once deleted, variables cannot be recovered. Proceed (y/[n])? y


In [ ]:
%whos

Interactive namespace is empty.


In [ ]:
#심플한 파이선의 철학
import this

The Zen of Python, by Tim Peters

Beautiful is better than ugly.
Explicit is better than implicit.
Simple is better than complex.
Complex is better than complicated.
Flat is better than nested.
Sparse is better than dense.
Readability counts.
Special cases aren't special enough to break the rules.
Although practicality beats purity.
Errors should never pass silently.
Unless explicitly silenced.
In the face of ambiguity, refuse the temptation to guess.
There should be one-- and preferably only one --obvious way to do it.
Although that way may not be obvious at first unless you're Dutch.
Now is better than never.
Although never is often better than *right* now.
If the implementation is hard to explain, it's a bad idea.
If the implementation is easy to explain, it may be a good idea.
Namespaces are one honking great idea -- let's do more of those!
