<a href="https://colab.research.google.com/github/tjdude/python/blob/main/lesson_03_numpy_3_modules_statistics%2C_lin%2Clogspace%2C_random.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Numpy modules

In [ ]:
import numpy as np

arr = [26, 28, 30, 35, 27, 31, 44]
arr = np.array(arr)
arr

array([26, 28, 30, 35, 27, 31, 44])

#### Statistics modules
    - max, min, median, mean, std, var
    - cov, corrcoef

In [ ]:
np.max(arr), np.min(arr), np.mean(arr), np.var(arr), np.std(arr)

(44, 26, 31.571428571428573, 33.38775510204081, 5.778213833187624)

#### linspace, logspace
    - linspace : 설정한 범위에서 선형적으로 분할한 위치의 값을 출력
    - logspace : 설정한 범위에서 로그로 분할한 위치의 값을 출력

In [ ]:
np.linspace(0, 100, 5)

array([  0.,  25.,  50.,  75., 100.])

##### logspace
    - log10(x1)=2, log_10(x_2)=4

In [ ]:
np.logspace(2, 4, 3)

array([  100.,  1000., 10000.])

##### 2000년 최저시급과 2019년 최저시급을 가정하여 선형적 증가 추세를 보고싶다면?

In [ ]:
time_00 = 1600
time_19 = 8350
np.linspace(time_00, time_19, 10)

array([1600., 2350., 3100., 3850., 4600., 5350., 6100., 6850., 7600.,
       8350.])

#### numpy random module
    - seed : 랜덤의 설정값
    - rand : 균등분포로 난수 생생
    - randn : 정규분포로 난수 생성
    - randint : 균등분포로 정수 생성
    - shuffle : 섞기
    - choice : 데이터를 특정 확률로 뽑기

##### seed

In [ ]:
np.random.seed(1)  # arbitrary
res1 = np.random.randint(10, 100, 10)

np.random.seed(2)
res2 = np.random.randint(10, 100, 10)

np.random.seed(1)
res3 = np.random.randint(10, 100, 10)

res1, res2, res3

(array([47, 22, 82, 19, 85, 15, 89, 74, 26, 11]),
 array([50, 25, 82, 32, 53, 92, 85, 17, 44, 59]),
 array([47, 22, 82, 19, 85, 15, 89, 74, 26, 11]))

##### rand

In [ ]:
np.random.rand(10)

array([0.18626021, 0.34556073, 0.39676747, 0.53881673, 0.41919451,
       0.6852195 , 0.20445225, 0.87811744, 0.02738759, 0.67046751])

In [ ]:
np.random.rand(10)

array([0.4173048 , 0.55868983, 0.14038694, 0.19810149, 0.80074457,
       0.96826158, 0.31342418, 0.69232262, 0.87638915, 0.89460666])

In [ ]:
np.random.rand(10)

array([0.41919451, 0.6852195 , 0.20445225, 0.87811744, 0.02738759,
       0.67046751, 0.4173048 , 0.55868983, 0.14038694, 0.19810149])

##### randn

In [ ]:
np.random.randn(10)

array([ 1.13376944, -1.09989127, -0.17242821, -0.87785842,  0.04221375,
        0.58281521, -1.10061918,  1.14472371,  0.90159072,  0.50249434])

##### randint

In [ ]:
x = np.random.randint(1, 10, (4, 4))
x

array([[7, 7, 1, 1],
       [3, 7, 1, 7],
       [8, 1, 4, 1],
       [4, 5, 8, 6]])

In [ ]:
np.random.shuffle(x)
x

array([[4, 5, 8, 6],
       [3, 7, 1, 7],
       [7, 7, 1, 1],
       [8, 1, 4, 1]])