<a href="https://colab.research.google.com/github/tjdude/python/blob/main/lesson_02_numpy_2_matrix_operation%2C_quiz.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### numpy로 작성하는 행렬

#### 행렬의 합

$$
    \begin{pmatrix}
    1 & 2 & 3 \\
    4 & 5 & 6 \\
    \end{pmatrix}
    +
    \begin{pmatrix}
    4 & 5 & 6 \\
    1 & 2 & 3 \\
    \end{pmatrix}
$$
   

#### 기본적인 list 연산도 구현 가능?

In [10]:
A = [[1, 2, 3], [4, 5, 6]]
B = [[4, 5, 6], [1, 2, 3]]
A + B # ? 

[[1, 2, 3], [4, 5, 6], [4, 5, 6], [1, 2, 3]]

#####  list에서 요소들의 합 구현은 이중 for문을 사용해야 한다.

In [11]:
res = [[c+d for c, d in zip(a, b)] for a, b in zip(A, B)]
res

[[5, 7, 9], [5, 7, 9]]

##### numpy array라면 어떨까?

In [12]:
import numpy as np
a = np.array(A)
b = np.array(B)
a+b

array([[5, 7, 9],
       [5, 7, 9]])

In [13]:
np.multiply(A,b)

array([[ 4, 10, 18],
       [ 4, 10, 18]])

### 행렬의 곱

$$
    \begin{pmatrix}
    1 & 2 & 3 \\
    4 & 5 & 6 \\
    \end{pmatrix}
    \rm{x}
    \begin{pmatrix}
    6 & 5 \\
    4 & 3 \\
    2 & 1 \\
    \end{pmatrix}
$$

In [14]:
a.shape, b.shape

((2, 3), (2, 3))

#### 굳이 list로 만들어서 하겠다면...

In [5]:
A = [[1, 2, 3], [4, 5, 6]]
B = [[6, 5], [4, 3], [2, 1]]

res = [[sum(a*b for a, b in zip(A_row,B_col)) for B_col in zip(*B)] for A_row in A]
res

[[20, 14], [56, 41]]

##### zip(*)

$$
    \begin{pmatrix}
    1 & 2 & 3 \\
    4 & 5 & 6 \\
    \end{pmatrix}
    →
    \begin{pmatrix}
    1 & 4 \\
    2 & 5 \\
    3 & 6 \\
    \end{pmatrix}
$$

In [ ]:
ls = [[1, 2, 3], [4, 5, 6]]
ls

[[1, 2, 3], [4, 5, 6]]

In [ ]:
ls2 = list(map(list, zip(*ls)))
ls2

[[1, 4], [2, 5], [3, 6]]

#### numpy 곱

In [15]:
a = np.array(A)
b = np.array(B).reshape(3,2)
np.dot(a,b) , a @ b

(array([[22, 16],
        [58, 43]]), array([[22, 16],
        [58, 43]]))

In [18]:
arr = np.array([[2,10,15],[1,2,3]])  #shape (2,3)

arr1 = np.array([1]) # (1,)

arr2 = np.array([1,2,3]) # (3,)

arr, arr1, arr2

(array([[ 2, 10, 15],
        [ 1,  2,  3]]), array([1]), array([1, 2, 3]))

In [19]:
arr.shape, arr1.shape, arr2.shape

((2, 3), (1,), (3,))

In [20]:
arr + arr1

array([[ 3, 11, 16],
       [ 2,  3,  4]])

In [21]:
arr + arr2, arr * arr2

(array([[ 3, 12, 18],
        [ 2,  4,  6]]), array([[ 2, 20, 45],
        [ 1,  4,  9]]))

In [23]:
a = np.array([[ 0,  0,  0],
              [10, 10, 10],
              [20, 20, 20],
              [30, 30, 30]])

b = np.array([1,2,3])
a*b

array([[ 0,  0,  0],
       [10, 20, 30],
       [20, 40, 60],
       [30, 60, 90]])

In [24]:
a.shape (4,3,2)
b.shape (  5,2)

TypeError: ignored

#### 행렬 데이터의 결합
    concatenate

In [26]:
r1 = np.array([[1, 9, 8], [7, 0, 2]])
r2 = np.array([[1, 8], [2, 2], [0, 2]])
r3 = np.array([[7, 6, 0], [3, 5, 4], [6, 7, 9]])

In [28]:
np.concatenate((r1, r3), axis=0)
# np.vstack([r1,r3])
# np.r_[r1,r3]

array([[1, 9, 8],
       [7, 0, 2],
       [7, 6, 0],
       [3, 5, 4],
       [6, 7, 9]])

배열을 옆으로 붙이기 (axis=1)

In [29]:
np.concatenate((r2, r3), axis=1)
np.hstack([r2,r3])
np.c_[r2,r3]

array([[1, 8, 7, 6, 0],
       [2, 2, 3, 5, 4],
       [0, 2, 6, 7, 9]])

In [30]:
ls1 = np.array([1, 2, 3])
ls2 = np.array([4, 5, 6])
np.c_[ls1, ls2] 

array([[1, 4],
       [2, 5],
       [3, 6]])

In [31]:
np.r_[ls1, ls2]

array([1, 2, 3, 4, 5, 6])

### Quiz
    위 행렬의 곱을 for문으로 작성하면?

In [34]:
A = [[1, 2, 3], [4, 5, 6]]
B = [[6, 5],[4, 3], [2, 1]]
print(len(A), len(B))

2 3


In [35]:
res = [[0 for i in range(len(B[0]))]for _ in range(len(A))]
for i in range(len(A)): # 행
    for j in range(len(B[0])): # 행
        for k in range(len(A[0])):
            res[i][j] += A[i][k] * B[k][j]
            
res

[[20, 14], [56, 41]]

In [36]:
a=np.array(A)
b=np.array(B)
np.dot(a,b)

array([[20, 14],
       [56, 41]])

n 차원 배열의 슬라이싱

In [37]:
a = np.arrange(0,9).reshape(3,3)
a

AttributeError: ignored

In [38]:
a[0], a[0:1], a[:,0]

(array([1, 2, 3]), array([[1, 2, 3]]), array([1, 4]))